POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer your_token_here

{
        "title": "Token_create_middleware",
        "author": "Token_create_middleware",
        "url": "www.Token_create_middleware.com",
        "likes": 50
}

###

GET http://localhost:3001/api/blogs/