POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "your_username_here",
    "name": "your_name_here",
    "password": "your_password_here"
}

###

GET http://localhost:3001/api/users